# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce90608eaef6d913893cebe5104ec6de8f983b1566153c75ddead7ee1ab29fab36301719b75d792b6a099ade2df04d1dad04c6ec0f0561f768298ca597d38712

test:
  secret_key_base: d7aef544c89e41056eb5fbfb122dbafc0bf5cadf5c9323cec2bd1368da0ac7e1c856031d3819481035e8dac6d3439e2ac411a63fa622cf863d66ea4cb90bf6b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
